{{/*
charts/feature-engine-svc/templates/serviceaccount.yaml
This template defines the Kubernetes ServiceAccount for the feature-engine-svc.
It is only created if .Values.serviceAccount.create is set to true.
*/}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "feature-engine-svc.serviceAccountName" . }}
  labels:
    {{- include "feature-engine-svc.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
