# charts/qsn-infra/Chart.yaml
# This is the Chart definition for the QSN infrastructure umbrella chart.
# It packages all third-party dependencies (Kafka, Cassandra, etc.) into a single,
# manageable chart.

apiVersion: v2
name: qsn-infra
description: A Helm umbrella chart for deploying the Quantum Sentinel Nexus infrastructure dependencies.
type: application
version: 1.0.0
appVersion: "1.0.0"

# The 'dependencies' section is the core of an umbrella chart.
# It lists all the sub-charts that will be installed when this chart is deployed.
# We are using stable and well-maintained charts from the Bitnami repository.
dependencies:
  # Apache Kafka for the core message bus
  - name: kafka
    version: "26.3.3" # Use a specific, tested version
    repository: "https://charts.bitnami.com/bitnami"
    alias: kafka
    # Conditions can be used to enable/disable parts of the chart from values.yaml
    condition: kafka.enabled

  # Apache Cassandra for the primary transaction data store
  - name: cassandra
    version: "11.1.3"
    repository: "https://charts.bitnami.com/bitnami"
    alias: cassandra
    condition: cassandra.enabled

  # Neo4j for the graph database (threat intelligence)
  - name: neo4j
    version: "5.12.0"
    repository: "https://neo4j.github.io/helm-charts"
    alias: neo4j
    condition: neo4j.enabled

  # Redis for caching and rate-limiting
  - name: redis
    version: "18.19.1"
    repository: "https://charts.bitnami.com/bitnami"
    alias: redis
    condition: redis.enabled

  # MinIO for S3-compatible object storage (e.g., for ML models)
  - name: minio
    version: "14.6.5"
    repository: "https://charts.bitnami.com/bitnami"
    alias: minio
    condition: minio.enabled

  # Istio base components for the service mesh
  - name: base
    version: "1.23.0"
    repository: "https://istio-release.storage.googleapis.com/charts"
    alias: istio-base
    condition: istio.enabled

  # Istio discovery service (istiod)
  - name: istiod
    version: "1.23.0"
    repository: "https://istio-release.storage.googleapis.com/charts"
    alias: istiod
    condition: istio.enabled

