{{/*
charts/scoring-svc/templates/deployment.yaml
This template defines the Kubernetes Deployment for the scoring-svc.
*/}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scoring-svc.fullname" . }}
  labels:
    {{- include "scoring-svc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "scoring-svc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "scoring-svc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "scoring-svc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
          # Liveness and readiness probes are crucial for a gRPC service.
          # We use 'grpc-health-probe' which should be included in the container image.
          # This checks if the gRPC server is responsive.
          livenessProbe:
            exec:
              command: ["/bin/grpc-health-probe", "-addr=:50051"]
            initialDelaySeconds: 10
          readinessProbe:
            exec:
              command: ["/bin/grpc-health-probe", "-addr=:50051"]
            initialDelaySeconds: 5
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
