{{/*
charts/fl-coordinator-svc/templates/deployment.yaml
This template defines the Kubernetes Deployment for the fl-coordinator-svc.
*/}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fl-coordinator-svc.fullname" . }}
  labels:
    {{- include "fl-coordinator-svc.labels" . | nindent 4 }}
spec:
  # The FL Coordinator is a singleton, so only one replica is needed.
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fl-coordinator-svc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fl-coordinator-svc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fl-coordinator-svc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 50052
              protocol: TCP
          # Liveness and readiness probes for a gRPC service.
          # This assumes a gRPC health check endpoint is implemented in the service.
          # For simplicity, we can use a TCP socket check as a basic probe.
          livenessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
