# charts/ingestion-svc/values.yaml
# Default configuration values for the ingestion-svc Helm chart.

# replicaCount specifies the number of pods to run for this service.
# For local development, 1 is sufficient. In production, this would be higher.
replicaCount: 1

image:
  # The repository where the Docker image is stored.
  # Tilt will override this with its own build, e.g., 'qsn/ingestion-svc'.
  repository: your-docker-registry/ingestion-svc
  # The policy for pulling the image. 'IfNotPresent' is good for local dev.
  pullPolicy: IfNotPresent
  # The tag of the image to deploy. This should be updated for new releases.
  tag: "latest"

# imagePullSecrets is a list of secrets needed to pull images from a private registry.
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created.
  create: true
  # Annotations to add to the service account.
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podSecurityContext:
  # Run as a non-root user for security.
  runAsNonRoot: true
  runAsUser: 1001
  fsGroup: 1001

securityContext:
  # Disallow privilege escalation.
  allowPrivilegeEscalation: false
  # Drop all Linux capabilities.
  capabilities:
    drop:
    - ALL
  # Make the root filesystem read-only.
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "istio" # Use the Istio ingress controller
  annotations:
    # Add any necessary Istio-specific annotations here.
    # kubernetes.io/ingress.class: istio
  hosts:
    - host: ingestion.qsn.local # A local hostname for the service
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  # We are commenting out resource requests and limits for local development
  # to avoid issues on resource-constrained machines. In production, these
  # should be carefully configured.
  # limits:
  #   cpu: 200m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

# Environment variables to be injected into the service container.
# These values are read by the Go application at startup.
env:
  # The address of the Kafka brokers.
  # This value typically points to the Kafka service within the Kubernetes cluster.
  KAFKA_BROKERS: "qsn-infra-kafka:9092"

  # The default Kafka topic to publish messages to.
  KAFKA_TOPIC: "txn-raw"

