{{/*
charts/edge-node-agent/templates/serviceaccount.yaml
This template defines the Kubernetes ServiceAccount for the edge-node-agent.
It is only created if .Values.serviceAccount.create is set to true.
*/}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "edge-node-agent.serviceAccountName" . }}
  labels:
    {{- include "edge-node-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
