{{/*
charts/alert-router-svc/templates/ingress.yaml
This template defines the Kubernetes Ingress resource for the alert-router-svc.
It is only created if .Values.ingress.enabled is set to true.
*/}}
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "alert-router-svc.fullname" . }}
  labels:
    {{- include "alert-router-svc.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "alert-router-svc.fullname" $ }}
                port:
                  # This should match the name of the WebSocket port in the Service definition.
                  name: ws
          {{- end }}
    {{- end }}
{{- end }}
