{{/*
charts/alert-router-svc/templates/serviceaccount.yaml
This template defines the Kubernetes ServiceAccount for the alert-router-svc.
It is only created if .Values.serviceAccount.create is set to true.
*/}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alert-router-svc.serviceAccountName" . }}
  labels:
    {{- include "alert-router-svc.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
